# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 856)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 1061, 201))
        self.groupBox.setObjectName("groupBox")
        self.firstNameLabel = QtWidgets.QLabel(self.groupBox)
        self.firstNameLabel.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.prenomInput = QtWidgets.QLineEdit(self.groupBox)
        self.prenomInput.setGeometry(QtCore.QRect(50, 60, 113, 22))
        self.prenomInput.setObjectName("prenomInput")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 111, 16))
        self.label_2.setObjectName("label_2")
        self.nomdefmilleinput = QtWidgets.QLineEdit(self.groupBox)
        self.nomdefmilleinput.setGeometry(QtCore.QRect(50, 130, 113, 22))
        self.nomdefmilleinput.setObjectName("nomdefmilleinput")
        self.emailInput = QtWidgets.QLineEdit(self.groupBox)
        self.emailInput.setGeometry(QtCore.QRect(230, 60, 261, 22))
        self.emailInput.setObjectName("emailInput")
        self.firstNameLabel_2 = QtWidgets.QLabel(self.groupBox)
        self.firstNameLabel_2.setGeometry(QtCore.QRect(230, 40, 81, 16))
        self.firstNameLabel_2.setObjectName("firstNameLabel_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 1061, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Adresseinput = QtWidgets.QTextEdit(self.groupBox_3)
        self.Adresseinput.setGeometry(QtCore.QRect(40, 70, 321, 87))
        self.Adresseinput.setObjectName("Adresseinput")
        self.firstNameLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        self.firstNameLabel_3.setGeometry(QtCore.QRect(40, 40, 81, 16))
        self.firstNameLabel_3.setObjectName("firstNameLabel_3")
        self.Telephone = QtWidgets.QLabel(self.groupBox_3)
        self.Telephone.setGeometry(QtCore.QRect(670, 40, 81, 16))
        self.Telephone.setObjectName("Telephone")
        self.telephoneinput = QtWidgets.QLineEdit(self.groupBox_3)
        self.telephoneinput.setGeometry(QtCore.QRect(670, 70, 261, 22))
        self.telephoneinput.setObjectName("telephoneinput")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 450, 1061, 331))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Tempsdetravailinput = QtWidgets.QLineEdit(self.groupBox_2)
        self.Tempsdetravailinput.setGeometry(QtCore.QRect(20, 100, 141, 41))
        self.Tempsdetravailinput.setObjectName("Tempsdetravailinput")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 121, 16))
        self.label_3.setObjectName("label_3")
        self.Savebutton = QtWidgets.QPushButton(self.groupBox_2)
        self.Savebutton.setGeometry(QtCore.QRect(922, 267, 111, 41))
        self.Savebutton.setObjectName("Savebutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Informations personnelles"))
        self.firstNameLabel.setText(_translate("MainWindow", "Prénom"))
        self.label_2.setText(_translate("MainWindow", "Nom de famille"))
        self.firstNameLabel_2.setText(_translate("MainWindow", "Email"))
        self.groupBox_3.setTitle(_translate("MainWindow", "     Détails du contact"))
        self.firstNameLabel_3.setText(_translate("MainWindow", "Adresse"))
        self.Telephone.setText(_translate("MainWindow", "Telephone"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Calendrier de travail"))
        self.label_3.setText(_translate("MainWindow", "Temps de travail"))
        self.Savebutton.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
