# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ADD DELETE.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editAdditem = QtWidgets.QLineEdit(self.centralwidget)
        self.editAdditem.setGeometry(QtCore.QRect(240, 230, 181, 31))
        self.editAdditem.setObjectName("editAdditem")
        self.lblAdditem = QtWidgets.QLabel(self.centralwidget)
        self.lblAdditem.setGeometry(QtCore.QRect(100, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblAdditem.setFont(font)
        self.lblAdditem.setObjectName("lblAdditem")
        self.pbAdditem = QtWidgets.QPushButton(self.centralwidget)
        self.pbAdditem.setGeometry(QtCore.QRect(120, 280, 311, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pbAdditem.setFont(font)
        self.pbAdditem.setObjectName("pbAdditem")
        self.pbDeleteitem = QtWidgets.QPushButton(self.centralwidget)
        self.pbDeleteitem.setGeometry(QtCore.QRect(120, 320, 311, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pbDeleteitem.setFont(font)
        self.pbDeleteitem.setObjectName("pbDeleteitem")
        self.lisBox = QtWidgets.QListWidget(self.centralwidget)
        self.lisBox.setGeometry(QtCore.QRect(105, 20, 321, 192))
        self.lisBox.setObjectName("lisBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblAdditem.setText(_translate("MainWindow", "Employes"))
        self.pbAdditem.setText(_translate("MainWindow", "ADD"))
        self.pbDeleteitem.setText(_translate("MainWindow", "DELETE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
